// <auto-generated />
using System;
using ORIGINAL_DAO.Manager_REFERENCE_ONLY.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ORIGINAL_DAO.Manager_REFERENCE_ONLY.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Assembly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssemblyFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OutputType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProjectFilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectStyle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TargetFramework")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UniqueIdentifier");

                    b.ToTable("Assemblies");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.AssemblyDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SourceAssemblyId")
                        .HasColumnType("int");

                    b.Property<int>("TargetAssemblyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TargetAssemblyId");

                    b.HasIndex("SourceAssemblyId", "TargetAssemblyId")
                        .IsUnique();

                    b.ToTable("AssemblyDependencies");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.AssemblyReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HintPath")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("AssemblyReferences");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.PackageReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDevelopmentDependency")
                        .HasColumnType("bit");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PackageName");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "PackageName", "Version")
                        .IsUnique();

                    b.ToTable("PackageReferences");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GuidDeterminationMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProjectStyle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("TargetFramework")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisualStudioGuid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FilePath");

                    b.HasIndex("ScanId");

                    b.HasIndex("ScanId", "UniqueIdentifier")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.ProjectDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<int>("SourceProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TargetProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.HasIndex("TargetProjectId");

                    b.HasIndex("SourceProjectId", "TargetProjectId")
                        .IsUnique();

                    b.ToTable("ProjectDependencies");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Scan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GitCommitHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortCommitHash")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ScanDate");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Solution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GuidDeterminationMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsSingleProjectSolution")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisualStudioGuid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.HasIndex("ScanId", "UniqueIdentifier")
                        .IsUnique();

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.SolutionProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<int>("SolutionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ScanId");

                    b.HasIndex("SolutionId", "ProjectId")
                        .IsUnique();

                    b.ToTable("SolutionProjects");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Assembly", b =>
                {
                    b.HasOne("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Project", "Project")
                        .WithMany("Assemblies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.AssemblyDependency", b =>
                {
                    b.HasOne("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Assembly", "SourceAssembly")
                        .WithMany("DependenciesFrom")
                        .HasForeignKey("SourceAssemblyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Assembly", "TargetAssembly")
                        .WithMany("DependenciesTo")
                        .HasForeignKey("TargetAssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceAssembly");

                    b.Navigation("TargetAssembly");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.AssemblyReference", b =>
                {
                    b.HasOne("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Project", "Project")
                        .WithMany("AssemblyReferences")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.PackageReference", b =>
                {
                    b.HasOne("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Project", "Project")
                        .WithMany("PackageReferences")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Project", b =>
                {
                    b.HasOne("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Scan", "Scan")
                        .WithMany("Projects")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.ProjectDependency", b =>
                {
                    b.HasOne("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Scan", "Scan")
                        .WithMany("ProjectDependencies")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Project", "SourceProject")
                        .WithMany("DependenciesFrom")
                        .HasForeignKey("SourceProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Project", "TargetProject")
                        .WithMany("DependenciesTo")
                        .HasForeignKey("TargetProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Scan");

                    b.Navigation("SourceProject");

                    b.Navigation("TargetProject");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Solution", b =>
                {
                    b.HasOne("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Scan", "Scan")
                        .WithMany("Solutions")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.SolutionProject", b =>
                {
                    b.HasOne("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Project", "Project")
                        .WithMany("SolutionProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Scan", "Scan")
                        .WithMany("SolutionProjects")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Solution", "Solution")
                        .WithMany("SolutionProjects")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Scan");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Assembly", b =>
                {
                    b.Navigation("DependenciesFrom");

                    b.Navigation("DependenciesTo");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Project", b =>
                {
                    b.Navigation("Assemblies");

                    b.Navigation("AssemblyReferences");

                    b.Navigation("DependenciesFrom");

                    b.Navigation("DependenciesTo");

                    b.Navigation("PackageReferences");

                    b.Navigation("SolutionProjects");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Scan", b =>
                {
                    b.Navigation("ProjectDependencies");

                    b.Navigation("Projects");

                    b.Navigation("SolutionProjects");

                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("ORIGINAL_DAO.Manager_REFERENCE_ONLY.Models.Solution", b =>
                {
                    b.Navigation("SolutionProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
