// <auto-generated />
using System;
using DAO.Manager.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAO.Manager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260211023115_FixCircularCascadePaths")]
    partial class FixCircularCascadePaths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssemblyDependencies", b =>
                {
                    b.Property<int>("ReferencingAssemblyId")
                        .HasColumnType("int");

                    b.Property<int>("ReferencedAssemblyId")
                        .HasColumnType("int");

                    b.HasKey("ReferencingAssemblyId", "ReferencedAssemblyId");

                    b.HasIndex("ReferencedAssemblyId");

                    b.ToTable("AssemblyDependencies");
                });

            modelBuilder.Entity("DAO.Manager.Data.Models.Entities.Assembly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ScanId");

                    b.HasIndex("ScanId", "FilePath")
                        .IsUnique();

                    b.ToTable("Assemblies", (string)null);
                });

            modelBuilder.Entity("DAO.Manager.Data.Models.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ScanId");

                    b.HasIndex("ScanId", "Name", "Version")
                        .IsUnique();

                    b.ToTable("Packages", (string)null);
                });

            modelBuilder.Entity("DAO.Manager.Data.Models.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("TargetFramework")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisualStudioGuid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FilePath");

                    b.HasIndex("Name");

                    b.HasIndex("ScanId");

                    b.HasIndex("ScanId", "UniqueIdentifier")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("DAO.Manager.Data.Models.Entities.Scan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GitCommit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ScanDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GitCommit");

                    b.HasIndex("ScanDate");

                    b.ToTable("Scans", (string)null);
                });

            modelBuilder.Entity("DAO.Manager.Data.Models.Entities.ScanEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.HasIndex("ScanId", "OccurredAt");

                    b.ToTable("ScanEvents", (string)null);
                });

            modelBuilder.Entity("DAO.Manager.Data.Models.Entities.Solution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisualStudioGuid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FilePath");

                    b.HasIndex("ScanId");

                    b.HasIndex("ScanId", "UniqueIdentifier")
                        .IsUnique();

                    b.ToTable("Solutions", (string)null);
                });

            modelBuilder.Entity("ProjectAssemblyReferences", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("AssemblyId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "AssemblyId");

                    b.HasIndex("AssemblyId");

                    b.ToTable("ProjectAssemblyReferences");
                });

            modelBuilder.Entity("ProjectPackageReferences", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "PackageId");

                    b.HasIndex("PackageId");

                    b.ToTable("ProjectPackageReferences");
                });

            modelBuilder.Entity("ProjectReferences", b =>
                {
                    b.Property<int>("ReferencingProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ReferencedProjectId")
                        .HasColumnType("int");

                    b.HasKey("ReferencingProjectId", "ReferencedProjectId");

                    b.HasIndex("ReferencedProjectId");

                    b.ToTable("ProjectReferences");
                });

            modelBuilder.Entity("SolutionProjects", b =>
                {
                    b.Property<int>("SolutionId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("SolutionId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("SolutionProjects");
                });

            modelBuilder.Entity("AssemblyDependencies", b =>
                {
                    b.HasOne("DAO.Manager.Data.Models.Entities.Assembly", null)
                        .WithMany()
                        .HasForeignKey("ReferencedAssemblyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DAO.Manager.Data.Models.Entities.Assembly", null)
                        .WithMany()
                        .HasForeignKey("ReferencingAssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAO.Manager.Data.Models.Entities.Assembly", b =>
                {
                    b.HasOne("DAO.Manager.Data.Models.Entities.Scan", "Scan")
                        .WithMany("Assemblies")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("DAO.Manager.Data.Models.Entities.Package", b =>
                {
                    b.HasOne("DAO.Manager.Data.Models.Entities.Scan", "Scan")
                        .WithMany("Packages")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("DAO.Manager.Data.Models.Entities.Project", b =>
                {
                    b.HasOne("DAO.Manager.Data.Models.Entities.Scan", "Scan")
                        .WithMany("Projects")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("DAO.Manager.Data.Models.Entities.ScanEvent", b =>
                {
                    b.HasOne("DAO.Manager.Data.Models.Entities.Scan", "Scan")
                        .WithMany("ScanEvents")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("DAO.Manager.Data.Models.Entities.Solution", b =>
                {
                    b.HasOne("DAO.Manager.Data.Models.Entities.Scan", "Scan")
                        .WithMany("Solutions")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("ProjectAssemblyReferences", b =>
                {
                    b.HasOne("DAO.Manager.Data.Models.Entities.Assembly", null)
                        .WithMany()
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DAO.Manager.Data.Models.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectPackageReferences", b =>
                {
                    b.HasOne("DAO.Manager.Data.Models.Entities.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DAO.Manager.Data.Models.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectReferences", b =>
                {
                    b.HasOne("DAO.Manager.Data.Models.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ReferencedProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DAO.Manager.Data.Models.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ReferencingProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolutionProjects", b =>
                {
                    b.HasOne("DAO.Manager.Data.Models.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAO.Manager.Data.Models.Entities.Solution", null)
                        .WithMany()
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DAO.Manager.Data.Models.Entities.Scan", b =>
                {
                    b.Navigation("Assemblies");

                    b.Navigation("Packages");

                    b.Navigation("Projects");

                    b.Navigation("ScanEvents");

                    b.Navigation("Solutions");
                });
#pragma warning restore 612, 618
        }
    }
}
